steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/qwiklabs-gcp-01-1cf185d065c9/my-app:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/qwiklabs-gcp-01-1cf185d065c9/my-app:latest']

  # Step 3: Deploy the image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

# Optional: Substitutions for dynamic variables
substitutions:
  _CLUSTER_NAME: 'my-cluster'
  _COMPUTE_ZONE: 'asia-south1'

# Optional: Timeout for the build
timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/qwiklabs-gcp-01-1cf185d065c9/my-app:latest'
