apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-app
  template:
    metadata:
      labels:
        app: gke-app
    spec:
      containers:
      - name: gke-app
        image: gcr.io/YOUR_PROJECT_ID/gke-app:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: gke-app-service
spec:
  selector:
    app: gke-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
